/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/dancer.glb -o src/components/Dancer.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect, useRef, useState } from "react";

export function Dancer(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/dancer.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  const [currentAnimation, setCurrentAnimation] = useState("wave")
  
  useEffect(() => {
    if (!actions || !actions[currentAnimation]) return;

    const action = actions[currentAnimation];
    console.log(action);
    
    action.reset().fadeIn(0.5).play();

    return () => {
      action.fadeOut(0.5);
    };
  }, [actions, currentAnimation]);
  
  return (
		<group
			ref={group}
			{...props}
			dispose={null}
			scale={0.01}
			position-y={0.8}
			onClick={() => {
				setCurrentAnimation((prev) => {
					if (prev === "wave") return "windmill";
					return "wave";
				});
			}}
		>
			<group name="AuxScene">
				<group position={[0, -82.942, -1.295]}>
					<primitive object={nodes.mixamorigHips} />
					<skinnedMesh
						name="Ch03"
						geometry={nodes.Ch03.geometry}
						material={materials.Ch03_Body}
						skeleton={nodes.Ch03.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/dancer.glb')
